import { Markdown } from "@/shared/ui/markdown";
import type { TimelineMessage } from "@/features/messages/types";

type HandoverNoteCardProps = {
  message: TimelineMessage;
  modelId: string;
};

/**
 * Labeled card for owner-triggered guided handover notes (#173).
 * Reuses the evidence-card frame: honest provenance "generated by <model>".
 */
export function HandoverNoteCard({ message, modelId }: HandoverNoteCardProps) {
  return (
    <section
      className="max-w-2xl rounded-lg border border-border/70 bg-muted/30 p-3 text-sm"
      data-testid="handover-note-card"
    >
      <div className="mb-3 flex flex-wrap items-baseline justify-between gap-2">
        <h3 className="font-medium text-foreground">Handover note</h3>
        <p
          className="text-2xs text-muted-foreground"
          data-testid="handover-note-provenance"
        >
          generated by {modelId}
        </p>
      </div>
      <Markdown content={message.body} className="text-sm" />
    </section>
  );
}
